M48
; DRILL file {KiCad 9.0.6} date 2026-01-28T18:22:54-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-28T18:22:54-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X96.0Y-86.5
X99.5Y-86.1
T2
X87.5Y-86.46
X87.5Y-89.0
X87.5Y-91.54
X87.5Y-94.08
M30
